[package]
name = "put_parameters"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1"
aws-config = { version = "1.1.7", features = ["behavior-version-latest"] }
aws-sdk-ssm = "1.54.0"
lambda_runtime = "0.13.0"
tokio = { version = "1", features = ["macros"] }
futures = "0.3.31"